// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLogistics.Data;

#nullable disable

namespace SmartLogistics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417125458_AddThoiGianLayHang")]
    partial class AddThoiGianLayHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("SmartLogistics.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SmartLogistics.Models.Customer", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("AdminId");

                    b.HasIndex("SoDienThoai");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SmartLogistics.Models.Incident", b =>
                {
                    b.Property<int>("MaSuCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuCo"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiSuCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChuyenDi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ViTriLat")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("ViTriLng")
                        .HasColumnType("decimal(10,7)");

                    b.HasKey("MaSuCo");

                    b.HasIndex("MaChuyenDi");

                    b.HasIndex("ThoiGian");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("SmartLogistics.Models.Order", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiemDenLat")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("DiemDenLng")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("DiemDiLat")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("DiemDiLng")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("DieuHanhId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("GiaCuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KhoiLuong")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TuyenDuong")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("AdminId");

                    b.HasIndex("DieuHanhId");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("NgayTao");

                    b.HasIndex("TrangThai");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SmartLogistics.Models.Trip", b =>
                {
                    b.Property<int>("MaChuyenDi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenDi"));

                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DieuHanhId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaXe")
                        .HasColumnType("int");

                    b.Property<string>("TaiXeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongKhoangCach")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaChuyenDi");

                    b.HasIndex("AdminId");

                    b.HasIndex("DieuHanhId");

                    b.HasIndex("MaXe");

                    b.HasIndex("TaiXeId");

                    b.HasIndex("TrangThai");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("SmartLogistics.Models.TripDetail", b =>
                {
                    b.Property<int>("MaChiTietChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietChuyen"));

                    b.Property<int>("MaChuyenDi")
                        .HasColumnType("int");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianLayHang")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiTietChuyen");

                    b.HasIndex("MaChuyenDi");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaChuyenDi", "MaDonHang")
                        .IsUnique();

                    b.ToTable("TripDetails");
                });

            modelBuilder.Entity("SmartLogistics.Models.TripLocation", b =>
                {
                    b.Property<int>("MaToaDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaToaDo"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<int>("MaChuyenDi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TocDo")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("MaToaDo");

                    b.HasIndex("MaChuyenDi");

                    b.HasIndex("ThoiGian");

                    b.ToTable("TripLocations");
                });

            modelBuilder.Entity("SmartLogistics.Models.Vehicle", b =>
                {
                    b.Property<int>("MaXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXe"));

                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DieuHanhId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiXe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaiXeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TrongTai")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MaXe");

                    b.HasIndex("AdminId");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("DieuHanhId");

                    b.HasIndex("TaiXeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SmartLogistics.Models.Admin", b =>
                {
                    b.HasBaseType("SmartLogistics.Models.AppUser");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("SmartLogistics.Models.DieuHanh", b =>
                {
                    b.HasBaseType("SmartLogistics.Models.AppUser");

                    b.ToTable("DieuHanhs", (string)null);
                });

            modelBuilder.Entity("SmartLogistics.Models.KeToan", b =>
                {
                    b.HasBaseType("SmartLogistics.Models.AppUser");

                    b.ToTable("KeToans", (string)null);
                });

            modelBuilder.Entity("SmartLogistics.Models.TaiXe", b =>
                {
                    b.HasBaseType("SmartLogistics.Models.AppUser");

                    b.Property<string>("DieuHanhId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("DieuHanhId");

                    b.ToTable("TaiXes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartLogistics.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartLogistics.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartLogistics.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLogistics.Models.AppUser", b =>
                {
                    b.HasOne("SmartLogistics.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("SmartLogistics.Models.Customer", b =>
                {
                    b.HasOne("SmartLogistics.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("SmartLogistics.Models.Incident", b =>
                {
                    b.HasOne("SmartLogistics.Models.Trip", "ChuyenDi")
                        .WithMany("Incidents")
                        .HasForeignKey("MaChuyenDi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenDi");
                });

            modelBuilder.Entity("SmartLogistics.Models.Order", b =>
                {
                    b.HasOne("SmartLogistics.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLogistics.Models.DieuHanh", "DieuHanh")
                        .WithMany()
                        .HasForeignKey("DieuHanhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLogistics.Models.Customer", "KhachHang")
                        .WithMany("Orders")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("DieuHanh");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("SmartLogistics.Models.Trip", b =>
                {
                    b.HasOne("SmartLogistics.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLogistics.Models.DieuHanh", "DieuHanh")
                        .WithMany()
                        .HasForeignKey("DieuHanhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLogistics.Models.Vehicle", "Xe")
                        .WithMany("Trips")
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartLogistics.Models.TaiXe", "TaiXe")
                        .WithMany()
                        .HasForeignKey("TaiXeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("DieuHanh");

                    b.Navigation("TaiXe");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("SmartLogistics.Models.TripDetail", b =>
                {
                    b.HasOne("SmartLogistics.Models.Trip", "ChuyenDi")
                        .WithMany("TripDetails")
                        .HasForeignKey("MaChuyenDi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLogistics.Models.Order", "DonHang")
                        .WithMany("TripDetails")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuyenDi");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("SmartLogistics.Models.TripLocation", b =>
                {
                    b.HasOne("SmartLogistics.Models.Trip", "ChuyenDi")
                        .WithMany("TripLocations")
                        .HasForeignKey("MaChuyenDi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenDi");
                });

            modelBuilder.Entity("SmartLogistics.Models.Vehicle", b =>
                {
                    b.HasOne("SmartLogistics.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLogistics.Models.DieuHanh", "DieuHanh")
                        .WithMany()
                        .HasForeignKey("DieuHanhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLogistics.Models.TaiXe", "TaiXe")
                        .WithMany()
                        .HasForeignKey("TaiXeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("DieuHanh");

                    b.Navigation("TaiXe");
                });

            modelBuilder.Entity("SmartLogistics.Models.Admin", b =>
                {
                    b.HasOne("SmartLogistics.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SmartLogistics.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLogistics.Models.DieuHanh", b =>
                {
                    b.HasOne("SmartLogistics.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SmartLogistics.Models.DieuHanh", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLogistics.Models.KeToan", b =>
                {
                    b.HasOne("SmartLogistics.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SmartLogistics.Models.KeToan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLogistics.Models.TaiXe", b =>
                {
                    b.HasOne("SmartLogistics.Models.DieuHanh", "DieuHanh")
                        .WithMany("ManagedDrivers")
                        .HasForeignKey("DieuHanhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLogistics.Models.AppUser", null)
                        .WithOne()
                        .HasForeignKey("SmartLogistics.Models.TaiXe", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DieuHanh");
                });

            modelBuilder.Entity("SmartLogistics.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SmartLogistics.Models.Order", b =>
                {
                    b.Navigation("TripDetails");
                });

            modelBuilder.Entity("SmartLogistics.Models.Trip", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("TripDetails");

                    b.Navigation("TripLocations");
                });

            modelBuilder.Entity("SmartLogistics.Models.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("SmartLogistics.Models.DieuHanh", b =>
                {
                    b.Navigation("ManagedDrivers");
                });
#pragma warning restore 612, 618
        }
    }
}
